try:
    assert 2 + 2 == 5, "Math error!"
except AssertionError as e:
    print(e)